name: Beam payment app CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "app/**/*.(js|tsx|ts)"
      - ".github/workflows/app*"
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-18.04
    container: 
      image: node:12.18.3

    steps:
      - uses: actions/checkout@v2

      - name: install and test
        run: |
          cd app
          yarn install --frozen-lockfile
          yarn test

  cd:
    runs-on: ubuntu-18.04
    container: 
      image: node:12.18.3

    steps:
      - uses: actions/checkout@v2

      - name: install and deploy
        run: |
          npm install -g appcenter-cli
          cd app
          yarn install --frozen-lockfile
          yarn deploy
          
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
