name: Beam payment app CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "app/**/*.(js|tsx|ts)"
      - ".github/workflows/app*"
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-18.04
    container: 
      image: node:12.18.3

    steps:
      - uses: actions/checkout@v2

      - name: install and test
        run: |
          cd app
          yarn install --frozen-lockfile
          yarn test

  cd:
    runs-on: ubuntu-18.04
    needs: ci
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: |
          cd app
          yarn install --frozen-lockfile

      - name: Deploy
        uses: joabalea/App-Center-action@v1.0.2
        with:
          command: |
            cd app
            appcenter codepush release-react -d Production
          token: ${{ secrets.APPCENTER_ACCESS_TOKEN }}
