name: Beam payment app CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "app/**/*.(js|tsx|ts)"
      - ".github/workflows/app*"
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: app

jobs:
  ci:
    runs-on: ubuntu-18.04
    container: 
      image: node:12.18.3

    steps:
      - uses: actions/checkout@v2

      - name: install and test
        run: |
          yarn install --frozen-lockfile
          yarn test
